EventsApplication/Controllers/Interested_EventsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EventsApplication.Data;
using EventsApplication.Models;
using System.Diagnostics;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;
using Microsoft.AspNetCore.Http;
using EventsApplication.Areas.Identity.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNet.Identity;
using System.Data;


namespace EventsApplication.Controllers
{
    public class Interested_EventsController : Controller
    {
        private readonly EventsApplicationContext _context;
        private readonly AuthDbContext _AuthContext;
        private readonly Microsoft.AspNetCore.Identity.UserManager<EventsApplicationUser> _userManager;


        public Interested_EventsController(EventsApplicationContext context, AuthDbContext context2, Microsoft.AspNetCore.Identity.UserManager<EventsApplicationUser> userManager)
        {
            _context = context;
            _AuthContext = context2;
            _userManager = userManager;
        }
        protected Microsoft.AspNetCore.Identity.UserManager<EventsApplicationUser> UserManager { get; set; }

        // GET: Events
        public async Task<IActionResult> Index()
        {

            var user = await _userManager.GetUserAsync(User);
            string ID = user.Id;
            var InterestedEventsIDs = from e in _context.InterestedUserEvents where e.UserId.Equals(user.Id) select e.EventId;
            
            
            List<Event> Events = new List<Event>();
            
            foreach (var item in InterestedEventsIDs)
            {
               var Event = from e in _context.Event where e.Id.Equals(item) select e;
               Events.Add(Event.FirstOrDefault());
            }



            var eventTypeVM = new EventTypeViewModel
            {

                Events = Events
            };

            return View(eventTypeVM);


            
        }
    }
}

EventsApplication/Views/Interested_Events/Index.cshtml
@model EventsApplication.Models.EventTypeViewModel
@using Microsoft.AspNetCore.Identity
@using EventsApplication.Areas.Identity.Data

@inject UserManager<EventsApplicationUser> UserManager

@{
    ViewData["Title"] = "Interested Events";
}

<form asp-controller="Interested_Events" asp-action="Index" method="get">
    
</form>
<br />

<div class="container">
    @foreach (var item in Model.Events)
    {
        <div class="row">
            <div class="col-3">

                @{string url = item.filename;}
                <img src="~/css/Images/@url" alt="Alternate Text" width="200" height="200" />
            </div>


            <div class="col-7">
                <p>Type: @item.Type</p>
                <p>Owner: @item.Owner</p>
                <p>@Html.DisplayFor(modelItem => item.Description)</p>

            </div>
            <div class="col-1">
                Date:
                @Html.DisplayFor(modelItem => item.ReleaseDate)
                Price: £@Html.DisplayFor(modelItem => item.Price)

            </div>
            
            

        </div>
        <br />
    }
</div>